services:
  # mvc:
  #   build: ./mvc
  #   container_name: spring_mvc
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/benchmarkdb
  #     - SPRING_DATASOURCE_USERNAME=benchmark
  #     - SPRING_DATASOURCE_PASSWORD=benchmark
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: 1024M

  # webflux:
  #   build: ./webflux
  #   container_name: spring_webflux
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/benchmarkdb
  #     - SPRING_R2DBC_USERNAME=benchmark
  #     - SPRING_R2DBC_PASSWORD=benchmark
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: 1024M

  nextjs:
    build: ./nextjs
    container_name: benchmark_nextjs
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://benchmark:benchmark@postgres:5432/benchmarkdb
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M

  django:
    build: ./django
    container_name: benchmark_django
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://benchmark:benchmark@postgres:5432/benchmarkdb
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M

  postgres:
    image: postgres:17
    container_name: benchmark_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: benchmarkdb
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M

volumes:
  pgdata:
